### ISSUE TITLE
Plural-Forms for French is wrong and it breaks the whole application

### ISSUE THREAD

**Issue by jajm** [omeka-s-modules/IiifPresentation#3]
Plural-Forms for French should be `nplurals=2; plural=(n > 1);` but currently it's `nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;`

When locale is set to French, enabling IiifPresentation breaks the whole application. The following error is displayed on all pages (when `APPLICATION_ENV` is set to `development`):

```
Laminas\I18n\Exception\RuntimeException
Plural rule of merging text domain is not compatible with the current one

Détails :

Laminas\I18n\Exception\RuntimeException: Plural rule of merging text domain is not compatible with the current one in /home/omekas/omeka-s/vendor/laminas/laminas-i18n/src/Translator/TextDomain.php:100
Stack trace:
#0 /home/omekas/omeka-s/vendor/laminas/laminas-i18n/src/Translator/Translator.php(705): Laminas\I18n\Translator\TextDomain->merge()
#1 /home/omekas/omeka-s/vendor/laminas/laminas-i18n/src/Translator/Translator.php(616): Laminas\I18n\Translator\Translator->loadMessagesFromPatterns()
#2 /home/omekas/omeka-s/vendor/laminas/laminas-i18n/src/Translator/Translator.php(440): Laminas\I18n\Translator\Translator->loadMessages()
#3 /home/omekas/omeka-s/vendor/laminas/laminas-i18n/src/Translator/Translator.php(355): Laminas\I18n\Translator\Translator->getTranslatedMessage()
#4 /home/omekas/omeka-s/application/src/I18n/Translator.php(25): Laminas\I18n\Translator\Translator->translate()
#5 /home/omekas/omeka-s/vendor/laminas/laminas-mvc-i18n/src/Translator.php(71): Omeka\I18n\Translator->translate()
#6 /home/omekas/omeka-s/application/src/Mvc/Controller/Plugin/Translate.php(37): Laminas\Mvc\I18n\Translator->translate()
#7 [internal function]: Omeka\Mvc\Controller\Plugin\Translate->__invoke()
#8 /home/omekas/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(275): call_user_func_array()
#9 /home/omekas/omeka-s/application/src/Controller/Admin/ModuleController.php(70): Laminas\Mvc\Controller\AbstractController->__call()
#10 /home/omekas/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(77): Omeka\Controller\Admin\ModuleController->browseAction()
#11 /home/omekas/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#12 /home/omekas/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#13 /home/omekas/omeka-s/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\EventManager\EventManager->triggerEventUntil()
#14 /home/omekas/omeka-s/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\Mvc\Controller\AbstractController->dispatch()
#15 /home/omekas/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\Mvc\DispatchListener->onDispatch()
#16 /home/omekas/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\EventManager\EventManager->triggerListeners()
#17 /home/omekas/omeka-s/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\EventManager\EventManager->triggerEventUntil()
#18 /home/omekas/omeka-s/index.php(21): Laminas\Mvc\Application->run()
#19 {main}
```

**Comment by jimsafley** [comment]
I can't reproduce this. The plural rule is correct. Transifex recently updated plural rules for some languages, and we updated the modules to reflect the update. What versions of Omeka and IiifPresentation are you running?

**Comment by jajm** [comment]
I tested this on Omeka S 3.2.3 (I modified `module.ini` to be able to) with IiiifPresentation v1.0.0
The Plural-Forms for fr.po are different in Omeka S 3.2 (nplurals=2) and in 4.0 (nplurals=3) (modified in f63a44caf5225e1e288d885a6d6bede666d6e5cd)

Are you sure the plural rule is correct in Omeka 4 and in this module ?
`msginit -l fr` and http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html both say `nplurals=2; plural=(n > 1);`

**Comment by jajm** [comment]
Related: https://github.com/omeka-s-modules/Osii/issues/4

**Comment by jajm** [comment]
It looks like it was fixed in v4.0.0 by omeka/omeka-s@e410377755d0d599722a029faf5d728672dc82b3
But the different plural rules are strange. Are you sure it's not a Transifex bug ?

**Comment by jimsafley** [comment]
It's not a bug. Apparently it reflects a change to the underlying standard. https://community.transifex.com/t/important-update-languages-plural-rules/2832

**Comment by jajm** [comment]
Okay.. TIL my language has 3 plural forms :)
Thanks for the link
